path=(/usr/local/sbin /usr/local/bin /usr/local/share/python /usr/texbin $path)

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="robbyrussell"
#export ZSH_THEME="sorin"
#export ZSH_THEME="lightsorin"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(osx brew vi-mode pip)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# General tweaks
setopt AUTO_CD
setopt AUTO_PUSHD
setopt AUTO_NAME_DIRS
setopt GLOB_COMPLETE
setopt PUSHD_MINUS
# setopt PUSHD_SILENT
setopt PUSHD_TO_HOME
setopt PUSHD_IGNORE_DUPS
setopt RM_STAR_WAIT # wait 10s before deletes
setopt ZLE
setopt NO_FLOW_CONTROL # disables ctrl-s
setopt NO_CLOBBER
setopt NO_BEEP

# History tweaks
HISTFILE=~/.history
SAVEHIST=10000
HISTSIZE=10000

setopt APPEND_HISTORY # don't overwrite history; append instead
setopt INC_APPEND_HISTORY # append after each command
setopt SHARE_HISTORY # share history between shells
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE
setopt HIST_VERIFY
setopt EXTENDED_HISTORY
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS


export EDITOR="vi"

# zsh performance tweaks
# .. take the first part of the path to be exact
zstyle ':completion:*' accept-exact '*(N)' 
# .. use a cache file
zstyle ':completion:*' use-cache on 
# .. and then specify the cache file to use (not added to repo: separate file for each machine)
zstyle ':completion:*' cache-path ~/.zshcache 


zstyle ':completion:*:*:killall:*' menu yes select
zstyle ':completion:*:killall:*'   force-list always

unsetopt correct_all

#bindkey '^[[A' history-search-backward
#bindkey '^[[B' history-search-forward
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^[[3~' delete-char
bindkey '^[3;5~' delete-char
#normal movement keys
#bindkey -e
#vim movement keys
bindkey -v

alias l="ls -Glh"
alias ll="ls -Glah"
alias .="pwd"
alias ..="cd .."
alias cd..="cd .."
alias rm="rm -i"
alias cp="cp -i"
alias matlab='matlab -nodesktop -nosplash'
alias ack='ack --smart-case'
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport'
alias netinfo='/Users/fedfol/coding/netinfo.pl'
alias e="mvim"

# mpc wrapper
alias m='/Users/fedfol/coding/mpc_scripts/mars/mars.py'
alias mrt='/Users/fedfol/coding/mpc_scripts/mars/mars.py rt'
alias mcd='/Users/fedfol/coding/mpc_scripts/mars/mars.py cd'

# Autojump
if [ -f `brew --prefix`/etc/autojump.zsh ]; then
  source `brew --prefix`/etc/autojump.zsh
fi

# FASD
eval "$(fasd --init auto)"

alias v='f -e mvim' # quick opening files with vim
alias o='a -e open' # quick opening files with xdg-open
